[alembic]
script_location = migrations
sqlalchemy.url = driver://user:pass@localhost/dbname

[loggers]
keys = root, alembic

[handlers]
keys = stream

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = stream

[logger_alembic]
level = INFO
handlers = stream
qualname = alembic

[handler_stream]
class = logging.StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %Y-%m-%d %H:%M:%S
